views
fkyeaseaking/TestGuru pull request #7
Opened 2021-12-16 17:09 UTC by fkyeaseaking

2021-12-17 05:35 UTC, VidgarVii requested changes

2021-12-17 05:35 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @questions = @test.questions
важно:
ТЗ: "Список вопросов теста должен выводиться **на той же странице, что и сам тест**"
другими словами нужна страница для вывода теста
что приводит к следующим выводам:
- экшен `index` в классе `QuestionsController` лишний
- вызов коллбека для `index` не нужен
- список вопросов нужно выводить на странице теста
- путь `test_questions_path`, который ты используешь в экшенах, тоже лишний (нужно отменить его создание в `routes`)
- нужен контроллер для ресурса `:tests` (его написание было поэтапно продемонстрировано в скринкасте)

2021-12-17 05:35 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  before_action :find_test, except: %i[show edit update destroy]
что бы показать вопрос. Знать тест не нужно.  А вот для создания вопроса. Нужен тест

2021-12-17 05:35 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @test = @question.test
инстанс переменная тест тут лишшняя. Тут после редиректа мы ни какие данные во вью не отправляем

2021-12-17 05:35 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    case action
для определения создается ресурс или редактируется
лучше использовать хелперы `.persisted?` или `.new_record?`

передавай в метод объект вопроса и по его состоянию ориентируйся что происходит (редактирование или создание)

2021-12-17 05:35 UTC, VidgarVii commented on app/views/layouts/_footer.html.erb
> +<p><%= year %> Kirill Kozyrev <%= link_to "Test Guru", github_url("fkyeaseaking", "TestGuru"), target: "_blank", rel: "nofollow" %></p>
используй `link_to` внутри хэлпера, а здесь просто вызывай его: `<%= github_url('name', 'test_guru') %>`
текст ссылки `TestGuru` можно также передавать третьим параметром в хэлпер
возможно имеет смысл сделать [keyword arguments](https://robots.thoughtbot.com/ruby-2-keyword-arguments): `<%= github_url(author: 'name', repo: 'test_guru', title: 'TestGuru') %>`

2021-12-17 05:35 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +    Time.zone.now.year
Time.current.year

2021-12-17 05:38 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +      "Edit #{@question.test.title} question"
ни когда не ориентируйся на глобальное пространство. От сюда и баг. Если хелпер создан, значит его можно вызвать где угодно и когда угодно во вью. И он должен работать всегда, а не когде звёзды сойдутся. Безопасно когда метод работает только с теми данными которые приходят аргументами в данный метод

2022-01-18 19:44 UTC, fkyeaseaking commented on app/controllers/questions_controller.rb
> +  before_action :find_test, except: %i[show edit update destroy]
у меня так и выходит, там стоит `except:`

2022-01-18 19:44 UTC, fkyeaseaking commented on app/controllers/questions_controller.rb
> +    @test = @question.test
мы же потом редиректим на этот тест

2022-01-19 07:39 UTC, VidgarVii requested changes

2022-01-19 07:39 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  before_action :find_test, except: %i[show edit update destroy]
не лучше использовать only?

2022-01-19 07:39 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @test = @question.test
у тебя в памяти вопрос остаётся. 
метод destroy удаляет запись из бд
после удаления можно также обратиться к вопросу и получить тест
redirect_to @question.test

2022-01-19 07:39 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :find_test, except: %i[index new create]
если друг появится новый экшен. то скорей всего придётся его дописывать тут. Лучше использовать only вместо except
Так же приходится додумывать где ж тогда используется find_test

2022-01-19 07:39 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +  def year
что это за year? Это год твоего рождения? Надо уточняй. По названию метода должно быть понятно. что метод возвращает или делает

2022-01-21 16:48 UTC, merged